language: node_js
node_js:
- 7.4.0
notifications:
  email: false
env:
  global:
  - NODE_ENV: test
before_install:
- npm install -g bower@1.8.0
- npm install -g gulp@3.9.1
- bower install
script:
- gulp
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: fZKmuWYExyxr2AxLJsyO+kk+AWAieaCDkQiT9B4PU+FSdIi3Esfx9Sn5fLXaB4/YZUpx7SMGpHcAP5DVxn83EXAtGKlCyvualdnkSFi9seZ76trsPF8uJ8/7qfNZEjTszygQTSc0dzMFSwR4pZce6n4o+ad1R4oLsXvEazuErTakJUKpZcRWmNjNRGlYfjnIcImEIxjT7YfMbbGGvKIHhdQOHTB0LhomHYdSwROqE4w3iEu3zALdwKRFwmo9vgvI1AmA5rVoOOgzNJ6gVrw0tZ8OQ/jvzyApS/09JoqF60JAuZ3MORqetQ8XxLtYYs5oMMdokGzzI7MweA9NRoA9RTdhEob9+vVzbCk6u59sqRcaGHXl8tTRNR+WUNRFBSt0LkUsrQksx5MxVydAMyn3Pg5ZfpFUgA5MpCkBD1P8aunnUamZv8OjVKF7XwsLrdFPzk0GewnrEKiuCOUtdF0YNBkj1s3MwRMLYhTaZDvCOyUUsF4vRKgNzotOlfRVGCSitiXQZbYkbrEhJRmY3NE5PXKhEEaMD52ZjR08ReWV9MqlYyFfhNRf/OsbxPwH3UOLph08ocv7eHRHWm5kA3zJDBIrecT7FZ25heASal/6MCt28pFod5pWiP1Ld9VIXqHYfLVq5Ft84s5NwBJpBDpyTRQq0LEMBVNH233kXnnZAnU=
  app: suntech-front
  on:
    repo: dhiegohenrique/suntech-front
  skip_cleanup: true
